apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "slintes.net.label.slintes.net/v1beta1",
          "kind": "Labels",
          "metadata": {
            "name": "labels-sample"
          },
          "spec": {
            "rules": [
              {
                "labels": [
                  "test.slintes.net/foo=bar"
                ],
                "nodeNamePatterns": [
                  "worker-0"
                ]
              }
            ]
          }
        },
        {
          "apiVersion": "slintes.net.label.slintes.net/v1beta1",
          "kind": "OwnedLabels",
          "metadata": {
            "name": "ownedlabels-sample"
          },
          "spec": {
            "domain": "test.slintes.net"
          }
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.4.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: tmp.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Labels is the Schema for the labels API
      displayName: Labels
      kind: Labels
      name: labels.slintes.net.label.slintes.net
      version: v1beta1
    - description: OwnedLabels is the Schema for the ownedlabels API They define which node labels are owned by this operator and can be removed in case no label rule matches
      displayName: Owned Labels
      kind: OwnedLabels
      name: ownedlabels.slintes.net.label.slintes.net
      version: v1beta1
  description: na
  displayName: Node Label Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - nodes
          verbs:
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - slintes.net.label.slintes.net
          resources:
          - labels
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - slintes.net.label.slintes.net
          resources:
          - labels/finalizers
          verbs:
          - update
        - apiGroups:
          - slintes.net.label.slintes.net
          resources:
          - labels/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - slintes.net.label.slintes.net
          resources:
          - ownedlabels
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - slintes.net.label.slintes.net
          resources:
          - ownedlabels/finalizers
          verbs:
          - update
        - apiGroups:
          - slintes.net.label.slintes.net
          resources:
          - ownedlabels/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: default
      deployments:
      - name: tmp-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=10
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                resources: {}
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                command:
                - /manager
                image: quay.io/slintes/node-label-operator:latest
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                ports:
                - containerPort: 9443
                  name: webhook-server
                  protocol: TCP
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 100m
                    memory: 30Mi
                  requests:
                    cpu: 100m
                    memory: 20Mi
                securityContext:
                  allowPrivilegeEscalation: false
                volumeMounts:
                - mountPath: /tmp/k8s-webhook-server/serving-certs
                  name: cert
                  readOnly: true
              securityContext:
                runAsNonRoot: true
              terminationGracePeriodSeconds: 10
              volumes:
              - name: cert
                secret:
                  defaultMode: 420
                  secretName: webhook-server-cert
      permissions:
      - rules:
        - apiGroups:
          - ""
          - coordination.k8s.io
          resources:
          - configmaps
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: default
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - na
  links:
  - name: Tmp
    url: https://tmp.domain
  maturity: alpha
  provider:
    name: na
    url: na
  version: 0.0.1
  webhookdefinitions:
  - admissionReviewVersions:
    - v1
    - v1beta1
    containerPort: 443
    deploymentName: tmp-controller-manager
    failurePolicy: Ignore
    generateName: mnode.kb.io
    rules:
    - apiGroups:
      - ""
      apiVersions:
      - v1
      operations:
      - CREATE
      - UPDATE
      resources:
      - nodes
    sideEffects: None
    targetPort: 9443
    type: MutatingAdmissionWebhook
    webhookPath: /label-v1-nodes
