# permissions for end users to view labels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: labels-viewer-role
rules:
- apiGroups:
  - slintes.net.label.slintes.net
  resources:
  - labels
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - slintes.net.label.slintes.net
  resources:
  - labels/status
  verbs:
  - get
