# permissions for end users to edit labels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: labels-editor-role
rules:
- apiGroups:
  - slintes.net.label.slintes.net
  resources:
  - labels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - slintes.net.label.slintes.net
  resources:
  - labels/status
  verbs:
  - get
