
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - slintes.net.label.slintes.net
  resources:
  - labels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - slintes.net.label.slintes.net
  resources:
  - labels/finalizers
  verbs:
  - update
- apiGroups:
  - slintes.net.label.slintes.net
  resources:
  - labels/status
  verbs:
  - get
  - patch
  - update
